name: build and push assets to release
on:
  release:
    types:
      - published
env:
  CONTAINER_RUN_OPTIONS: " "

jobs:
  release-assests:
    name: release glox
    runs-on: ubuntu-18.04
    steps:
      - name: checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: setup go
        uses: actions/setup-go@v3
        with:
          go-version: '^1.16.4'
      - name: build
        run: |
          go build
      - name: Uploading assets...
        uses: softprops/action-gh-release@v1
        with:
          files: |
            glox
            go.mod
